### ISSUE TITLE
Thin image

### ISSUE THREAD

**Issue by md5** [docker-infra/container_exporter#7]
It would be cool if there were a thinner `container-exporter` image. The `go:onbuild` base is currently 514MB and the layer that does the `go-wrapper download` is 72MB. The layer that does the `go install` itself is only 16MB, so I suspect a resulting thin image could be around that size.

The `swarm` image is a good example of this pattern: https://github.com/docker/swarm-library-image/blob/master/Dockerfile

I've also created a couple of them myself: https://github.com/synctree/docker-logstash-forwarder https://github.com/md5/docker-gen/tree/static-build-image

**Comment by discordianfish** [comment]
Hi @md5,

I simply have no build pipeline for that available so far. I hoped for some Docker native solution to this problem as proposed here:
- https://github.com/docker/docker/issues/7115
- https://github.com/docker/docker/issues/7149
- https://github.com/docker/docker/issues/8660
- https://groups.google.com/forum/#!topic/docker-dev/70rDCdOCjvM

Although this discussion is going on for over a year, nothing really materialized yet. That being said, I've planned to build small images for some go project we built, but didn't get to it yet. So will keep this open until we have a solution.

**Comment by md5** [comment]
Sounds good. Thanks for the response. I've been patiently waiting for docker/docker#7115 or something like it as well.

**Comment by discordianfish** [comment]
Hi @md5,

I switched to alpine linux for the base image and run everything in one step than cleans up afterwards. This brings down the image size to 21.75 MB which should be good for now :)

**Comment by discordianfish** [comment]
Hi @md5,

I switched to alpine linux for the base image and run everything in one step than cleans up afterwards. This brings down the image size to  27.01MB MB which should be good for now :)

**Comment by md5** [comment]
Thanks @discordianfish :+1:
